export const PROFILE_DATA_LOADING = 'PROFILE_DATA_LOADING';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const USER_REPO_DATA_LOADING = 'USER_REPO_DATA_LOADING';
export const USER_REPO_DATA_SUCCESS = 'USER_REPO_DATA_SUCCESS';